version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - instance:/instance # for sqlite
    command: sh -c "flask run --host=0.0.0.0 --port=8000"
    environment:
      - FLASK_APP=main
      - FLASK_ENV=development
      - JWT_SECRET_KEY=secret-key
      - DB_URL=sqlite:///data.db

volumes:
  instance: